name: Google App Engine Continous Deployment

on:
  pull_request:
    types:
    - closed
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Install Dependencies
      run: |
        python -m pip install pipenv
        pipenv install --dev

    - name: Create requirements.txt
      run: |
        pipenv lock -r > requirements.txt
    
    - name: Decrypt Cloud Storage service account
      run: |
        chmod +x .github/scripts/decrypt.sh
        ./.github/scripts/decrypt.sh
      env:
        SECRET_FILE_PASSPHRASE: ${{secrets.GS_SA_PASSPHRASE}}
        SECRET_FILE: ${{secrets.GS_SA_KEY}}
    
    - name: Create app.yaml
      run: |
        export VERSION=$(git rev-parse --short HEAD)
        pipenv run python app.yaml.py
      env:
        # Django
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
        DEBUG: ${{secrets.DEBUG}}

        # Email
        EMAIL_HOST_USER: ${{secrets.EMAIL_HOST_USER}}
        EMAIL_HOST_PASSWORD: ${{secrets.EMAIL_HOST_PASSWORD}}
        ADMINS: ${{secrets.ADMINS}}
        MANAGERS: ${{secrets.MANAGERS}}

        # Cloud Storage
        GS_BUCKET_NAME: ${{secrets.GS_BUCKET_NAME}}
        GS_SA_KEY: ${{secrets.GS_SA_KEY}}

        # Cloud SQL
        INSTANCE_CONNECTION_NAME: ${{secrets.INSTANCE_CONNECTION_NAME}}
        DATABASE: ${{secrets.DATABASE}}
        DB_USER: ${{secrets.DB_USER}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      
    - name: Decrypt App Engine service account
      run: |
        chmod +x .github/scripts/decrypt.sh
        ./.github/scripts/decrypt.sh
      env:
        SECRET_FILE_PASSPHRASE: ${{secrets.GAE_SA_PASSPHRASE}}
        SECRET_FILE: ${{secrets.GAE_SA_KEY}}
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
      
    steps:
    - name: Deploy to App Engine Standard
      run: |
        chmod +x .github/scripts/deploy-gae.sh
        ./.github/scripts/deploy-gae.sh
      env:
        GAE_SA_KEY: ${{secrets.GAE_SA_KEY }}
        GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
