name: Django CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Install Dependencies
      run: |
        pip install pipenv
        pipenv install --dev
    
    - name: Set up headless firefox and install geckodriver
      run: |
        chmod +x .github/scripts/selenium-setup.sh
        ./.github/scripts/selenium-setup.sh
    
    - name: Decrypt Cloud Storage service account credentials
      run: |
        chmod +x .github/scripts/decrypt.sh
        ./.github/scripts/decrypt.sh
      env:
        SECRET_FILE_PASSPHRASE: ${{secrets.GS_SA_PASSPHRASE}}
        SECRET_FILE: ${{secrets.GS_SA_KEY}}
    
    - name: Run Tests
      run: |
        pipenv run python manage.py test
      env:
        # Django
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
        DEBUG: ${{secrets.DEBUG}}

        # Email
        EMAIL_HOST_USER: ${{secrets.EMAIL_HOST_USER}}
        EMAIL_HOST_PASSWORD: ${{secrets.EMAIL_HOST_PASSWORD}}
        ADMINS: ${{secrets.ADMINS}}
        MANAGERS: ${{secrets.MANAGERS}}

        # Cloud Storage
        GS_BUCKET_NAME: ${{secrets.GS_BUCKET_NAME}}
        GS_SA_KEY: ${{secrets.GS_SA_KEY}}

    - name: Build Documentation
      run: |
        cd docs
        pipenv run make clean
        pipenv run make html
