name: Staging Deploy

on:
  pull_request:
    types:
    - closed
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Authenticate gcloud
      run: |
        chmod +x ./scripts/decrypt_secret.sh
        ./scripts/decrypt_secret.sh
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./secrets/raw/${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}
        SECRET_FILE: ${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}
        SECRET_FILE_PASSPHRASE: ${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE_PASSPHRASE}}

    - name: Deploy to App Engine Standard
      run: |
        pipenv run python manage.py collectstatic --no-input
        chmod +x ./scripts/deploy_to_app_engine.sh
        ./scripts/deploy_to_app_engine.sh
      env:
        # For deployment
        DJANGO_SETTINGS_MODULE: config.settings.production

        # Constants
        ADMINS: ${{secrets.ADMINS}}
        ADMIN_URL: ${{secrets.ADMIN_URL}}
        DATABASE_INSTANCE_CONNECTION_NAME: ${{secrets.DATABASE_INSTANCE_CONNECTION_NAME}}
        DJANGO_DEBUG: ${{secrets.DJANGO_DEBUG}}
        DJANGO_EMAIL_HOST_USER: ${{secrets.DJANGO_EMAIL_HOST_USER}}
        DJANGO_EMAIL_HOST_PASSWORD: ${{secrets.DJANGO_EMAIL_HOST_PASSWORD}}
        GOOGLE_APPLICATION_CREDENTIALS: ./secrets/raw/${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}
        GOOGLE_CLOUD_PROJECT: ${{secrets.GOOGLE_CLOUD_PROJECT}}
        SECRET_FILE: ${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}

        # Environment related
        APP_YAML: staging_app.yaml

        DJANGO_SECRET_KEY: ${{secrets.STAGING_SECRET_KEY}}
        DATABASE: ${{secrets.STAGING_DATABASE}}
        DB_USER: ${{secrets.STAGING_DB_USER}}
        DB_PASSWORD: ${{secrets.STAGING_DB_PASSWORD}}
        GCP_STORAGE_BUCKET_NAME: ${{secrets.STAGING_GCP_STORAGE_BUCKET_NAME}}
        ALLOWED_HOSTS: ${{secrets.STAGING_ALLOWED_HOSTS}}
