name: Staging Deploy

on:
  pull_request:
    types:
    - closed
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    
    - name: Authenticate gcloud
      run: |
        chmod +x .github/scripts/decrypt.sh
        ./.github/scripts/decrypt.sh
        gcloud auth activate-service-account --key-file=$SECRET_FILE
      env:
        SECRET_FILE: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        SECRET_FILE_PASSPHRASE: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS_PASSPHRASE}}
    
    - name: Collect Static Files
      run: pipenv run python manage.py collectstatic --no-input

    - name: Deploy to App Engine Standard
      run: |
        chmod +x ./scripts/deploy_to_app_engine.sh
        ./scripts/deploy_to_app_engine.sh
      env:
        APP_YAML: staging_app.yaml
        SECRET_FILE: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
    
    - name: Run Database Migrations
      run: pipenv run python manage.py migrate
